---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Para configurar um nó de controle do Ansible, identifique uma máquina virtual ou física com acesso de rede às portas de gerenciamento de todos os nós de arquivo e bloco que podem ser usados para configurar a solução. 
---
= Configure um nó de controle do Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para configurar um nó de controle do Ansible, você precisa designar uma máquina virtual ou física com acesso de rede a todos os nós de arquivo e bloco implantados na solução BeeGFS no NetApp.

Consulte link:beegfs-technology-requirements.html#ansible-control-node-requirements["Requisitos técnicos"]a para obter uma lista das versões de pacotes recomendadas. As etapas a seguir foram testadas no Ubuntu 22,04.04. Para obter passos específicos para a distribuição Linux preferida, consulte https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentação do Ansible"^] .

. A partir do nó de controle do Ansible, instale os seguintes pacotes Python e Python Virtual Environment.
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Crie um ambiente virtual Python.
+
[source, console]
----
python3 -m venv ~/pyenv
----
. Ative o ambiente virtual.
+
[source, console]
----
source ~/pyenv/bin/activate
----
. Instale os pacotes Python necessários dentro do ambiente virtual ativado.
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Instale a coleção BeeGFS usando o Ansible Galaxy.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. Verifique se as versões instaladas do Ansible, Python e a coleção BeeGFS correspondem ao link:beegfs-technology-requirements.html#ansible-control-node-requirements["Requisitos técnicos"].
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. Configure SSH sem senha para permitir que o Ansible acesse os nós de arquivo BeeGFS remotos a partir do nó de controle do Ansible.
+
.. No nó de controle do Ansible, se necessário, gere um par de chaves públicas.
+
[source, console]
----
ssh-keygen
----
.. Configure o SSH sem senha para cada um dos nós de arquivo.
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





CAUTION: *Not* configure SSH sem senha para os nós de bloco. Isto não é suportado nem necessário.
