---
sidebar: sidebar 
permalink: second-gen/beegfs-gens.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: A solução BeeGFS on NetApp está atualmente em seu segundo projeto geracional. 
---
= Projete gerações
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A solução BeeGFS on NetApp está atualmente em seu segundo projeto geracional.

A primeira e a segunda geração incluem uma arquitetura básica que incorpora um sistema de arquivos BeeGFS e um sistema de storage NVMe EF600. No entanto, a segunda geração baseia-se na primeira a incluir estes benefícios adicionais:

* Duplique o desempenho e a capacidade, adicionando apenas 2U GB de espaço em rack
* Alta disponibilidade (HA) com base em um design de hardware de duas camadas de disco compartilhado
* Arquitetura projetada para os sistemas NVIDIA DGX SuperPOD A100, H100, H200 e B200, que foi validada anteriormente em um cluster de aceitação dedicado na NVIDIA. Leia mais sobre o NVIDIA DGX SuperPOD com a NetApp no link:https://docs.netapp.com/us-en/netapp-solutions/ai/ai-dgx-superpod.html["guia de design"].




== Segundo design geracional

A segunda geração do BeeGFS no NetApp é otimizada para atender aos requisitos de performance de workloads exigentes, incluindo computação de alta performance (HPC), aprendizado de máquina (ML), deep learning (DL) e outras técnicas de inteligência artificial (AI). Ao incorporar uma arquitetura de alta disponibilidade (HA) de disco compartilhado, esse design garante a durabilidade e a disponibilidade dos dados, tornando-o ideal para empresas e outras organizações que não podem pagar tempo de inatividade ou perda de dados. O projeto de segunda geração inclui componentes como servidores PCIe Gen5 e suporte para switches InfiniBand NVIDIA Quantum QM9700 400GBGb/s. Essa solução não só foi verificada pela NetApp, mas também passou na qualificação externa como opção de storage para o SuperPOD do NVIDIA DGX™ A100, com certificação estendida para os sistemas DGX SuperPOD H100, H200 e B200.



== Primeiro design geracional

A primeira geração de BeeGFS no NetApp foi projetada para workloads de aprendizado de máquina (ML) e inteligência artificial (AI) usando os sistemas de storage NVMe NetApp EF600, o sistema de arquivos paralelos BeeGFS, os sistemas NVIDIA A100 e os switches IB NVIDIA Mellanox Quantum QM8700 200GBGb/s. Esse design também oferece InfiniBand (IB) de 200GB GB/s para a malha de interconexão de cluster de computação e storage para fornecer uma arquitetura totalmente baseada em IB para workloads de alto desempenho.

Para obter mais informações sobre a primeira geração, link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NetApp EF-Series AI com os sistemas DGX A100 e BeeGFS da NVIDIA"^]consulte .
