---
sidebar: sidebar 
permalink: second-gen/beegfs-technology-requirements.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Para implementar a solução BeeGFS no NetApp, verifique se seu ambiente atende aos requisitos de tecnologia. 
---
= Requisitos técnicos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para implementar a solução BeeGFS no NetApp, garanta que seu ambiente atenda aos requisitos de tecnologia descritos neste documento.



== Visão geral dos requisitos

Esta página detalha os requisitos de hardware, software e firmware para implementar o BeeGFS em NetApp building blocks. Os requisitos estão organizados nas seguintes seções:

* <<Requisitos de hardware>> - Nós de arquivo (hardware/software/firmware), nós de bloco (hardware/firmware), rede e cabeamento
* <<Requisitos de implantação de software>> - Componentes implantados pelo Ansible
* <<Requisitos de nó de controle do Ansible>> - Versões do software do nó de controle




== Requisitos de hardware

Antes de começar, certifique-se de que seu hardware atenda às seguintes especificações para um projeto de bloco único da solução BeeGFS na NetApp. Os componentes exatos para uma implementação específica podem variar de acordo com os requisitos do cliente. Cada nó de arquivo deve atender ou exceder essas especificações para atingir o desempenho esperado.



=== Requisitos de nó de arquivo

[cols="10%,90%"]
|===
| Quantidade | Especificações 


| 2  a| 
*Lenovo ThinkSystem SR665 V3*

*Hardware:*

* *Processadores:* 2x AMD EPYC 9124 16C 3.0 GHz (configurado como duas zonas NUMA)
* *Memória:* 256GBGB (16x 16GB TruDDR5 4800MHzGB RDIMM-A)
* *Expansão PCIe:* quatro slots PCIe Gen5 x16 (dois por zona NUMA)
* *Placas HCA:* 4x MCX755106AS-HEAT ConnectX-7, NDR200, QSFP112, 2-port, PCIe Gen5 x16, InfiniBand Adapter
* *Armazenamento:* Dois discos em RAID 1 para OS (1TB 7.2K SATA ou melhor)
* *Gerenciamento:* porta 1GbE para gerenciamento de SO em banda
* *BMC:* 1GbE BMC com API Redfish para gerenciamento de servidor fora de banda
* *Alimentação:* Duas fontes de alimentação de substituição a quente e ventoinhas de alto desempenho


*Software e Firmware:*

* *Sistema Operacional:* Red Hat 9.4 Server Físico com Alta Disponibilidade (2 socket)
* *Kernel Linux:* 5.14.0-427.42.1.el9_4.x86_64
* *Firmware HCA:* FW: 28.46.1006, PXE: 3.8.0100, UEFI: 14.39.0013


|===

IMPORTANT: Os nós de arquivo exigem uma assinatura válida do Red Hat Enterprise Linux Server e o Red Hat Enterprise Linux High Availability Add-On.



=== Requisitos do nó de bloco

Cada bloco de construção requer dois E-Series arrays do mesmo modelo. Não misture modelos de arrays dentro do mesmo bloco de construção.

[cols="10%,20%,70%"]
|===
| Quantidade | Modelo | Especificações 


| 2 | EF80  a| 
*Hardware:*

* *Memória:* 128GB (64GB por controlador)
* *Adaptador:* 2x 2-port 200Gb/NDR (NVMe/IB)
* *Drives:* Configuradas para corresponder aos metadados e à capacidade de storage desejados


*Firmware:*

* *SANtricity OS:* 12.00
* *NVSRAM:* NEF80-200834-D00
* *Firmware da unidade:* Versão mais recente disponível para seus modelos de unidade (consulte link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Site de firmware de disco e-Series"^])




| 2 | EF600  a| 
*Hardware:*

* *Memória:* 256GB (128GB por controlador)
* *Adaptador:* 2-port 200Gb/HDR (NVMe/IB)
* *Drives:* Configuradas para corresponder aos metadados e à capacidade de storage desejados


*Firmware:*

* *SANtricity OS:* 11.90R5
* *NVSRAM:* N6000-890834-D02
* *Firmware da unidade:* Versão mais recente disponível para seus modelos de unidade (consulte link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Site de firmware de disco e-Series"^])


|===


=== Requisitos do switch de rede de storage

[cols="10%,90%"]
|===
| Quantidade | Especificações 


| 1  a| 
*Switch NVIDIA QM9700 Quantum 2 NDR InfiniBand*

O switch de rede de storage deve ser capaz de 200Gb/s InfiniBand. O NVIDIA QM9700 é o switch recomendado para o cluster.

|===

NOTE: Switches alternativos, como o NVIDIA MQM8700 Quantum, podem ser usados, mas exigem cabeamento diferente.



=== Requisitos de cabeamento



==== Cabos de nó de bloco para nó de arquivo

As conexões diretas de nós de bloco para nós de arquivo requerem os seguintes cabos:

[cols="15%,60%,25%"]
|===
| Quantidade | Especificação do cabo | Comprimento 


| 8 | MCP1650-H001E30 - NVIDIA cabo de cobre passivo, QSFP56, 200Gb/s | 1 m 
|===


==== Cabos do nó de arquivo para o switch de storage

Os seguintes tipos de cabo são recomendados para o switch NVIDIA QM9700 Quantum 2. Escolha entre fibra ativa ou cobre passivo, de acordo com suas necessidades. As quantidades são por building block.

[cols="20%,15%,10%,55%"]
|===
| Modelo do interrutor | Tipo de cabo | Quantidade | Número de peça 


.4+| NVIDIA QM9700 .3+| Fibra ativa (incluindo transcetores) | 2 | MMA4Z00-NS (multimodo, IB/ETH, 800GB GB/s 2x400Gb/s OSFP de porta dupla) 


| 4 | MFP7E20-Nxxx (cabo de fibra divisor de 2 canais multimodo, 4 canais para dois) 


| 8 | MMA1Z00-NS400 (multimodo, IB/ETH, QSFP-112 de porta única de 400GB GB/s) 


| Cobre passivo | 2 | MCP7Y40-N002 (cabo divisor de cobre passivo NVIDIA, InfiniBand de 800GB GB/s para 4x 200GB GB/s, OSFP para 4x QSFP112 GB) 
|===


=== Requisitos de implantação de software

A tabela a seguir lista os requisitos de software implantados automaticamente como parte da implantação do BeeGFS baseada em Ansible.

[cols="20%,80%"]
|===
| Software | Versão 


| BeeGFS | 8.2.2 


| Corosync | 3,1.8-1 


| Pacemaker | 2,1.7-5,2 


| Agentes de vedação (peixe-vermelho/apc) | 4,10.0-62 


| Drivers InfiniBand / RDMA | DOCA-OFED-25.04-0.6.1 
|===


=== Requisitos de nó de controle do Ansible

A solução BeeGFS no NetApp é implantada e gerenciada a partir de um nó de controle do Ansible. Para obter mais informações, consulte https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html["Documentação do Ansible"^] .

Os requisitos de software listados nas tabelas a seguir são específicos da versão da coleção Ansible do NetApp BeeGFS listada abaixo.

[cols="30%,70%"]
|===
| Software | Versão 


| Ansible-core | >= 2.19.0 


| Python | 3,12 


| Pacotes Python adicionais | Cryptography-46.0.3, netaddr-1.3.0, ipaddr-2.2.0 


| Coleção BeeGFS do NetApp e-Series | 4.0.0 
|===