---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-prereqs.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Pré-requisitos para implantar o driver CSI do BeeGFS 
---
= Pré-requisitos para implantar o driver CSI do BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de implantar e configurar o driver CSI do BeeGFS, certifique-se de ter um cluster Kubernetes em execução, acesso ao seu cluster BeeGFS e as permissões apropriadas para instalar recursos em todo o cluster.



== Verificar configuração do Kubernetes

Execute o seguinte comando para verificar o status dos pods no seu cluster Kubernetes:

[source, console]
----
kubectl get pods
----
**Resultado esperado:**

[listing]
----
root@node01:/etc/cni/net.d# kubectl get pods
No resources found in default namespace.
----
Se nenhum pod estiver em execução, a lista estará vazia.  Caso contrário, os pods devem ser listados sem erros.



== Validar o cliente e os serviços da BeeGFS

Verifique se o cluster BeeGFS está íntegro e se todos os serviços estão acessíveis executando o seguinte comando:

**BeeGFS 7.4**

[source, console]
----
beegfs-check-servers
----
**BeeGFS 8**

[source, console]
----
beegfs health check
----

NOTE: O driver CSI funciona com ambos `beegfs-dkms-client` e `beegfs-client` , que deve ser instalado em cada nó do Kubernetes.  Para obter instruções de instalação, consulte a documentação do BeeGFS Client DKMS: https://doc.beegfs.io/latest/advanced_topics/client_dkms.html[]

**Saída esperada do BeeGFS 7.4:**

[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# beegfs-check-servers
Management
==========
mgmt [ID: 1]: reachable at XXX.X.AB.1:8008 (protocol: TCP)

Metadata
==========
meta_25_tgt_2501 [ID: 2501]: reachable at XXX.X.AA.MN:8255 (protocol: RDMA)
meta_26_tgt_2601 [ID: 2601]: reachable at XXX.X.BB.NO:8265 (protocol: RDMA)
meta_27_tgt_2701 [ID: 2701]: reachable at XXX.X.AA.OP:8275 (protocol: RDMA)
meta_28_tgt_2801 [ID: 2801]: reachable at XXX.X.BB.PQ:8285 (protocol: RDMA)
meta_29_tgt_2901 [ID: 2901]: reachable at XXX.X.AA.QR:8295 (protocol: RDMA)
meta_30_tgt_3001 [ID: 3001]: reachable at XXX.X.BB.RS:8305 (protocol: RDMA)
meta_31_tgt_3101 [ID: 3101]: reachable at XXX.X.AA.ST:8315 (protocol: RDMA)
meta_32_tgt_3201 [ID: 3201]: reachable at XXX.X.BB.TU:8325 (protocol: RDMA)

Storage
==========
stor_25_tgt_2501 [ID: 2501]: reachable at XXX.X.CC.MN:8253 (protocol: RDMA)
stor_26_tgt_2601 [ID: 2601]: reachable at XXX.X.DD.NO:8263 (protocol: RDMA)
stor_27_tgt_2701 [ID: 2701]: reachable at XXX.X.CC.OP:8273 (protocol: RDMA)
stor_28_tgt_2801 [ID: 2801]: reachable at XXX.X.DD.PQ:8283 (protocol: RDMA)
stor_29_tgt_2901 [ID: 2901]: reachable at XXX.X.CC.QR:8293 (protocol: RDMA)
stor_30_tgt_3001 [ID: 3001]: reachable at XXX.X.DD.RS:8303 (protocol: RDMA)
stor_31_tgt_3101 [ID: 3101]: reachable at XXX.X.CC.ST:8313 (protocol: RDMA)
stor_32_tgt_3201 [ID: 3201]: reachable at XXX.X.DD.32:8323 (protocol: RDMA)
----
Caso algum serviço esteja inacessível, verifique se o cliente BeeGFS está configurado corretamente e se a conectividade de rede com os servidores BeeGFS está funcionando.
