---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-verify.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Verificação da implantação do driver CSI do BeeGFS. 
---
= Verificação da implantação do driver CSI do BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para verificar se o driver CSI do BeeGFS foi implantado com sucesso, verifique o status dos pods do driver CSI e confirme se eles estão em execução conforme o esperado.

Para verificar o status de todos os recursos no namespace BeeGFS-CSI, execute:

[source, console]
----
kubectl get all -n beegfs-csi
----
**Resultado esperado:**

[listing]
----
NAME                          READY    STATUS      RESTARTS    AGE
pod/csi-beegfs-controller-0   3/3      Running     0           5d11h
pod/csi-beegfs-node-8f917     3/3      Running     0           5d11h
----


== Inspecione o módulo do controlador.

Para diagnosticar problemas ou obter mais detalhes sobre o pod do Controlador CSI do BeeGFS, use o seguinte comando para descrever o pod e revisar seus eventos, status e atividades recentes:

[source, console]
----
kubectl describe pod csi-beegfs-controller-0 -n beegfs-csi
----
**Resultado esperado:**

[listing]
----
Events:

  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  117s                 default-scheduler  Successfully assigned beegfs-csi/csi-beegfs-controller-0 to node01
  Normal   Pulled     117s                 kubelet            Container image "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0" already present on machine
  Normal   Created    117s                 kubelet            Created container: csi-provisioner
  Normal   Started    117s                 kubelet            Started container csi-provisioner
  Normal   Started    101s (x3 over 117s)  kubelet            Started container beegfs
  Normal   Pulled     86s (x2 over 117s)   kubelet            Container image "registry.k8s.io/sig-storage/csi-resizer:v1.11.1" already present on machine
  Normal   Created    86s (x2 over 117s)   kubelet            Created container: csi-resizer
  Normal   Started    86s (x2 over 117s)   kubelet            Started container csi-resizer
  Warning  BackOff    85s (x5 over 115s)   kubelet            Back-off restarting failed container beegfs in pod csi-beegfs-controller-0_beegfs-csi(47016fd3-3a2a-41ed-bc4c-5a716c377b1e)
  Normal   Pulled     73s (x4 over 117s)   kubelet            Container image "ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0" already present on machine
  Normal   Created    73s (x4 over 117s)   kubelet            Created container: beegfs
----


== Verificar classe de armazenamento

. Verifique se a StorageClass foi criada com sucesso:
+
[source, console]
----
kubectl get sc
----
+
**Resultado esperado:**

+
[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl get sc
NAME                PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-beegfs-dyn-sc   beegfs.csi.org.com   Delete          Immediate           true                   17s
----
. Confirme se o volume BeeGFS está montado conforme o esperado.
+
Verifique o diretório especificado como `volDirBasePath` em `examples/k8s/dyn/dyn-sc.yaml` aparece em `/mnt/beegfs` .

+
Por exemplo, se `volDirBasePath` está definido para `user_id_k8s` Você deverá ver este diretório listado:

+
[source, console]
----
root@node01:/# ls -ltr /mnt/beegfs/
total 1
drwxrwxrwx 4 root root 2 Oct 15 10:16 user_id_k8s
----

