---
sidebar: sidebar 
permalink: administer/clusters-upgrade-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Use o Ansible para atualizar o BeeGFS e o cluster de HA. 
---
= Atualizar os serviços BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Use o Ansible para atualizar a versão do BeeGFS em execução no seu cluster de alta disponibilidade.



== Visão geral

BeeGFS segue um `major.minor.patch` esquema de controle de versão. As funções do BeeGFS HA Ansible são fornecidas para cada versão com suporte `major.minor` (por exemplo, `beegfs_ha_7_2` e `beegfs_ha_7_3`). Cada função de HA é fixada à versão de patch BeeGFS mais recente disponível no momento do lançamento da coleção Ansible.

O Ansible deve ser usado para todas as atualizações do BeeGFS, incluindo a migração entre versões principais, secundárias e de correção do BeeGFS. Para atualizar o BeeGFS, você precisará primeiro atualizar a coleção Ansible do BeeGFS, o que também trará as correções e melhorias mais recentes para a automação de implantação/gerenciamento e o cluster de alta disponibilidade subjacente. Mesmo após atualizar para a versão mais recente da coleção, o BeeGFS não será atualizado até que  `ansible-playbook` seja executado com o  `-e "beegfs_ha_force_upgrade=true"` definido. Para detalhes adicionais sobre cada atualização, consulte a link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["Documentação do BeeGFS Upgrade"^] da sua versão atual.


NOTE: Se você estiver atualizando para o BeeGFS v8, consulte o link:clusters-upgrade-beegfs-v8.html["Atualize para BeeGFS v8"] procedimento em vez disso.



== Caminhos de atualização testados

Os seguintes caminhos de upgrade foram testados e verificados:

[cols="1,1,1,5"]
|===
| Versão original | Versão de atualização | Multirail | Detalhes 


| 7.2.6 | 7.3.2 | Sim | Atualizando a coleção beegfs de v3,0.1 para v3,1.0, multirail adicionado 


| 7.2.6 | 7.2.8 | Não | Atualizando a coleção beegfs de v3,0.1 para v3,1.0 


| 7.2.8 | 7.3.1 | Sim | Atualização usando beegfs coleção v3,1.0, multi-rail adicionado 


| 7.3.1 | 7.3.2 | Sim | Atualize usando a coleção beegfs v3,1.0 


| 7.3.2 | 7.4.1 | Sim | Atualize usando a coleção beegfs v3,2.0 


| 7.4.1 | 7.4.2 | Sim | Atualize usando a coleção beegfs v3,2.0 


| 7.4.2 | 7.4.6 | Sim | Atualize usando a coleção beegfs v3,2.0 


| 7.4.6 | 8,0 | Sim | Atualize usando as instruções no link:clusters-upgrade-beegfs-v8.html["Atualize para BeeGFS v8"] procedimento. 


| 7.4.6 | 8,1 | Sim | Atualize usando as instruções no link:clusters-upgrade-beegfs-v8.html["Atualize para BeeGFS v8"] procedimento. 


| 7.4.6 | 8,2 | Sim | Atualize usando as instruções no link:clusters-upgrade-beegfs-v8.html["Atualize para BeeGFS v8"] procedimento. 
|===


== Etapas de atualização do BeeGFS

As seções a seguir fornecem etapas para atualizar a coleção BeeGFS Ansible e o próprio BeeGFS. Preste atenção especial a qualquer passo extra para atualizar as versões BeeGFS Major ou menor.



=== Passo 1: Atualize a coleção BeeGFS

Para atualizações de coleção com acesso ao link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galaxy"^], execute o seguinte comando:

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
Para atualizações de coleção offline, faça o download da coleção link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galaxy"^]clicando no desejado `Install Version`` e,em seguida `Download tarball`, . Transfira o tarball para o nó de controle do Ansible e execute o seguinte comando.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
Consulte link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["Instalando coleções"^] para obter mais informações.



=== Etapa 2: Atualize o inventário do Ansible

Faça as atualizações necessárias ou desejadas nos arquivos de inventário do Ansible do seu cluster. Consulte a seção <<Notas de atualização da versão>> abaixo para detalhes sobre os requisitos específicos da sua atualização. Consulte a seção link:../custom/architectures-inventory-overview.html["Visão geral do Ansible Inventory"^] para informações gerais sobre como configurar o inventário BeeGFS HA.



=== Etapa 3: Atualizar o manual do Ansible (somente ao atualizar versões principais ou secundárias)

Se você estiver se movendo entre versões maiores ou menores, no `playbook.yml` arquivo usado para implantar e manter o cluster, atualize o nome da `beegfs_ha_<VERSION>` função para refletir a versão desejada. Por exemplo, se você quiser implantar o BeeGFS 7,4, isso `beegfs_ha_7_4` seria :

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
Para obter mais detalhes sobre o conteúdo deste arquivo de manual de estratégia, consulte link:../custom/architectures-deploy-ha-cluster.html["Implante o cluster BeeGFS HA"^]a seção.



=== Passo 4: Execute a atualização BeeGFS

Para aplicar a atualização BeeGFS:

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
Nos bastidores, o papel BeeGFS HA vai lidar com:

* Verifique se o cluster está no estado ideal com cada serviço BeeGFS localizado no nó preferido.
* Coloque o cluster no modo de manutenção.
* Atualize os componentes do cluster HA (se necessário).
* Atualize cada nó de arquivo, um de cada vez, da seguinte forma:
+
** Coloque-a em standby e faça failover de seus serviços para o nó secundário.
** Atualize os pacotes BeeGFS.
** Serviços de retorno.


* Mova o cluster para fora do modo de manutenção.




== Notas de atualização da versão



=== Atualização do BeeGFS versão 7.2.6 ou 7.3.0



==== Alterações na autenticação baseada em conexão

BeeGFS versão 7.3.2 e posteriores exigem que a autenticação baseada em conexão seja configurada. Os serviços não serão iniciados sem:

* Especificando um `connAuthFile`, ou
* Configuração `connDisableAuthentication=true` no arquivo de configuração do serviço.


É altamente recomendável habilitar autenticação baseada em conexão para segurança. Veja link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["Autenticação baseada em conexão BeeGFS"^] para mais informações.

As  `beegfs_ha*`funções geram e distribuem automaticamente o arquivo de autenticação para:

* Todos os nós de arquivo no cluster
* O nó de controle Ansible em `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`


A  `beegfs_client`função detectará e aplicará automaticamente este arquivo aos clientes quando estiver presente.


WARNING: Se você não utilizou o  `beegfs_client` papel para configurar os clientes, será necessário distribuir manualmente o arquivo de autenticação para cada cliente e configurar a configuração  `connAuthFile` no arquivo  `beegfs-client.conf`. Ao atualizar de uma versão do BeeGFS sem autenticação baseada em conexão, os clientes perderão o acesso, a menos que você desative a autenticação baseada em conexão durante a atualização, configurando  `beegfs_ha_conn_auth_enabled: false` em  `group_vars/ha_cluster.yml` (não recomendado).

Para obter detalhes adicionais e opções de configuração alternativas, consulte a etapa de configuração de autenticação de conexão na seção link:../custom/architectures-inventory-common-file-node-configuration.html["Especifique a Configuração do nó de ficheiro Comum"^].
