---
sidebar: sidebar 
permalink: administer/clusters-expand-shrink-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, replace 
summary: Adicione ou remova blocos de construção do cluster. 
---
= Expanda ou diminua o cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Adicione ou remova blocos de construção do cluster.



== Visão geral

Esta seção documenta várias considerações e opções para ajustar o tamanho do cluster BeeGFS HA. Normalmente, o tamanho do cluster é ajustado adicionando ou removendo componentes básicos, que geralmente são dois nós de arquivo configurados como um par de HA. Também é possível adicionar ou remover nós de arquivo individuais (ou outros tipos de nós de cluster), se necessário.



== Adicionando um Building Block ao cluster



=== Considerações

Aumentar o cluster adicionando componentes básicos adicionais é um processo simples. Antes de começar, lembre-se das restrições relativas ao número mínimo e máximo de nós de cluster em cada cluster de HA individual e determine se você deve adicionar nós ao cluster de HA existente ou criar um novo cluster de HA. Normalmente, cada componente básico consiste em dois nós de arquivo, mas três nós é o número mínimo de nós por cluster (para estabelecer quorum) e dez é o máximo recomendado (testado). Para cenários avançados, é possível adicionar um único nó "tiebreaker" que não executa nenhum serviço BeeGFS ao implantar um cluster de dois nós. Entre em Contato com o suporte da NetApp se você estiver pensando em tal implantação.

Tenha em mente essas restrições e qualquer crescimento futuro esperado de cluster ao decidir como expandir o cluster. Por exemplo, se você tiver um cluster de seis nós e precisar adicionar mais quatro nós, seria recomendável apenas iniciar um novo cluster de HA.


TIP: Lembre-se: Um único sistema de arquivos BeeGFS pode consistir em vários clusters de HA independentes. Isso permite que os sistemas de arquivos continuem dimensionando muito além dos limites recomendados/físicos dos componentes subjacentes do cluster de HA.



=== Passos

Ao adicionar um componente básico ao cluster, você precisará criar os `host_vars` arquivos para cada um dos novos nós de arquivo e nós de bloco (arrays e-Series). Os nomes desses hosts precisam ser adicionados ao inventário, juntamente com os novos recursos que devem ser criados. Os arquivos correspondentes `group_vars` precisarão ser criados para cada novo recurso. Consulte link:../custom/architectures-overview.html["use arquiteturas personalizadas"^]a secção para obter detalhes.

Depois de criar os arquivos corretos, tudo o que é necessário é executar novamente a automação usando o comando:

[source, console]
----
ansible-playbook -i <inventory>.yml <playbook>.yml
----


== Removendo um Building Block do cluster

Há uma série de considerações a ter em mente quando você precisa aposentar um bloco de construção, por exemplo:

* Quais serviços BeeGFS estão sendo executados nesse componente básico?
* Apenas os nós de arquivo estão se aposentando e os nós de bloco devem ser anexados a novos nós de arquivo?
* Se todo o componente básico estiver sendo aposentado, os dados devem ser movidos para um novo componente básico, dispersos em nós existentes no cluster ou movidos para um novo sistema de arquivos BeeGFS ou outro sistema de storage?
* Isso pode acontecer durante uma interrupção ou deve ser feito sem interrupções?
* O componente básico está ativamente em uso ou contém dados que não estão mais ativos?


Devido aos diversos pontos de partida possíveis e aos estados finais desejados, entre em Contato com o suporte da NetApp para que possamos identificar e ajudar a implementar a melhor estratégia com base em seu ambiente e requisitos.
